import { Fruit } from "../format/fruit";


export const FRUITS: Fruit[] = [
    {
        id: 1,
        nom: 'Fruit du gum gum',
        categorie: 'Paramecia',
        type: 'Elasticité',
        power: 'Elasticité  Confère au corps de l\'utilisateur l\'élasticité, le rendant insensible aux attaques physiques et à divers projectiles',
        picture: 'assets/1.jfif',
        detenteur: 'Monkey D. Luffy',
    },
    {
        id: 2,
        nom: 'Pyro-Fruit',
        categorie: 'Logia',
        type: 'Feu',
        power: 'Feu : le corps de celui qui le mange se transforme en feu. Il peut donc créer des déflagrations surpuissantes et contrôler les températures ambiantes.',
        picture: 'assets/2.jfif',
        detenteur: 'Sabo',
    },
    {
        id: 3,
        nom: 'Fruit des Ténèbres',
        categorie: 'Logia',
        type: 'Ténèbres',
        power: 'Ténèbres :le corps de celui qui le mange se transforme en ténèbres. Il devient capable de modifier la gravité afin d\'attirer à lui et d\'absorber à peu près n\'importe quoi dans un "trou noir" et de les relâcher par la suite.',
        picture: 'assets/3.jfif',
        detenteur: 'Marshall D. Teach (alias Barbe Noire)',
    },
    {
        id: 4,
        nom: 'Fruit du Phénix - mythique',
        categorie: 'Zoan',
        type: 'Phénix',
        power: 'Régénération du phénix',
        picture: 'assets/4.png',
        detenteur: 'Marco',
    },
    {
        id: 5,
        nom: 'Fruit Fumigène',
        categorie: 'Logia',
        type: 'Fumée',
        power: 'Fumée :  le corps de celui qui le mange se transforme en fumée.',
        picture: 'assets/5.jfif',
        detenteur: 'Smoker',
    },
    {
        id: 6,
        nom: 'Fruit des Éclosions',
        categorie: 'Paramecia',
        type: 'Eclosion',
        power: ' Permet de faire pousser des parties de son corps (ou même de créer des clones) partout où son utilisateur le désire, même sur une autre personne.',
        picture: 'assets/6.jfif',
        detenteur: 'Nico Robin',
    },
    {
        id: 7,
        nom: 'Fruit de l\'Humain - normal',
        categorie: 'Zoan',
        type: 'Humain',
        power: 'Celui qui le mange devient à moitié humain',
        picture: 'assets/7.jfif',
        detenteur: 'Tony-Tony Chopper',
    },
    {
        id: 8,
        nom: 'Fruit du Dinosaure - Allosaurus',
        categorie: 'Zoan',
        type: 'Dinosaure',
        power: 'Celui qui le mange peut se transformer en allosaurus',
        picture: 'assets/8.jfif',
        detenteur: 'X-Drake',
    },
    {
        id: 9,
        nom: 'Fruit du Pachyderme - Mammouth',
        categorie: 'Zoan',
        type: 'Mamouth',
        power: 'Celui qui le mange peut se transformer en mammouth.',
        picture: 'assets/9.png',
        detenteur: 'Jack',
    },
    {
        id: 10,
        nom: 'Fruit du Tremblement',
        categorie: 'Paramecia',
        type: 'Tremblement',
        power: 'Permet à son utilisateur de créer des ondes sismiques pour ainsi provoquer des tremblements de terre ou fissures (même dans l\'air ambiant) qui détruisent tout ce qui se trouve dans leurs zones d\'effet.',
        picture: 'assets/10.jfif',
        detenteur: 'Marshall D. Teach',
    },
    {
        id: 11,
        nom: 'Fruit du Bistouri',
        categorie: 'Paramecia',
        type: 'Bistouri',
        power: 'Ce fruit permet à celui qui le mange de créer une sphère dans laquelle il peut tout faire comme inter-changer quelque chose avec une autre ou allonger les portées de ses coups de sabre.',
        picture: 'assets/11.jfif',
        detenteur: 'Trafalgar D. Water Law',
    },
    {
        id: 12,
        nom: 'Fruit des Sables',
        categorie: 'Logia',
        type: 'Sable',
        power: 'le corps de celui qui le mange se transforme en sable. Il peut contrôler le sable à sa guise et peut assécher l\'humidité avec ses mains pouvant ainsi par exemple assécher l\'eau présente dans le corps de son adversaire et par conséquent le tuer, envoyer des vagues de sables, des lames de sables et des tempêtes de sable balayant tout sur son passage.',
        picture: 'assets/12.png',
        detenteur: 'Crocodile',
    },
    {
        id: 13,
        nom: 'Fulguro-Fruit',
        categorie: 'Logia',
        type: 'Foudre',
        power: 'le corps de celui qui le mange se transforme en foudre. Il peut donc se déplacer à la vitesse de la foudre et foudroyer n\'importe quoi mis à part les éléments non-conducteurs tels que le caoutchouc',
        picture: 'assets/13.jfif',
        detenteur: 'Ener',
    },
    {
        id: 14,
        nom: 'Fruit de l\'Ombre',
        categorie: 'Paramecia',
        type: 'Ombre',
        power: 'Permet à son utilisateur de contrôler les ombres. Il peut couper les ombres de n\'importe qui à l\'aide d\'une paire de ciseaux et les ombres ainsi retirées peuvent être enfermées dans des corps inertes, ce qui donne naissance à des zombies possédant les techniques de combat de la personne à qui appartenait l\'ombre.',
        picture: 'assets/14.png',
        detenteur: 'Gecko Moria',
    },
    {
        id: 15,
        nom: 'Fruit du Magma',
        categorie: 'Logia',
        type: 'Magma',
        power: 'le corps de celui qui le mange se transforme en lave. Il peut alors faire fondre tout ce qu\'il veut et quasiment n\'importe qui.',
        picture: 'assets/15.jfif',
        detenteur: 'Sakazuki',
    },
    {
        id: 16,
        nom: 'Fruit du démon artificiel de Végapunk',
        categorie: 'Zoan',
        type: 'Smile',
        power: 'il permet de se transformer en un dragon oriental.',
        picture: 'assets/16.jpg',
        detenteur: 'Momonosuké Kozuki',
    },
    {
        id: 17,
        nom: 'Fruit de la Résurrection',
        categorie: 'Paramecia',
        type: 'Résurrection',
        power: 'Permet au propriétaire de revenir à la vie une fois mort (ce pouvoir ne marche qu\'une seule fois).',
        picture: 'assets/17.jfif',
        detenteur: 'Brook',
    },
    {
        id: 18,
        nom: 'Fruit du Givre ',
        categorie: 'Paramecia',
        type: 'Givre',
        power: 'le corps de celui qui le mange se transforme en glace. Il est capable de geler n\'importe quoi et quasiment n\'importe qui, lancer des vagues surpuissantes d`\'air glacé qui peuvent tout geler sur leurs passages et est immunisé aux différentiels de température quand celui-ci intensifie le froid ambiant.',
        picture: 'assets/18.jfif',
        detenteur: 'Kuzan',
    },
]